project:
  type: website

website:
  title: "Health in the US"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: visualization.qmd
        text: Overview
      - href: model.qmd
        text: Model
      - href: disparities.qmd
        text: Disparities
      - href: sources.qmd
        text: Sources
      - href: about.qmd
        text: About

format:
  html:
    theme: lux
    css: styles.css
    toc: true



